apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.global.storageProvisioner }}
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nexus.pvcDataCapacity }}
  storageClassName: {{ .Values.global.storageClassData }}
  volumeMode: Filesystem
