apiVersion: v1
kind: Secret
data:
  admin-password: {{ .Values.global.nexusAdminPasswordB64 }}
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-app
type: Opaque
