= OpenDevStack Setup

This document will guide you through installing / maintaining an OpenDevStack installation.

NOTE: From now on we assume, you work from a Bash (Cygwin / Linux).

== Server prerequisites

In order to run the Atlassian suite and OpenShift, your host must have:

- At least 16GB RAM and 32GB of available disk space
- `vm.max_map_count=262144` to run SonarQube (which can be set via `sudo sysctl -w vm.max_map_count=262144`)
- A recent `git` version (>= 2.13.2)
- A recent `jq` version (>= 1.5, see https://stedolan.github.io/jq/)

== Local Setup

Before you can install OpenDevStack (no matter whether locally or on another server) you need to have the sources available on your local machine.

=== Repositories

If you do not have the ODS repositories setup yet, go to your Terminal and run:
[source,sh]
----
mkdir -p opendevstack
cd opendevstack
curl -LO https://raw.githubusercontent.com/opendevstack/ods-core/master/ods-setup/repos.sh
chmod +x repos.sh
----

If you are installing OpenDevStack for the first time, run:
[source,sh]
----
./repos.sh --init
----

If there is already an existing installation of OpenDevStack, run:
[source,sh]
----
./repos.sh
----

The script will prompt you which Git ref you want to use. Select either `master` for bleeding edge or a more stable "version" such as `2.x`. Afterwards running this script, all required repositories should be available locally.

=== Configuration

Before you get started with configuration, please refer to https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample[configuration sample page] for supported service versions.
Go to `ods-core` and run:
[source,sh]
----
make prepare-config
----

If you want to install OpenDevStack for the first time, leave the BitBucket URL empty.

After the configuration is prepared, fill out all the parameters for your installation and commit the result.

=== Tailor

We use https://github.com/opendevstack/tailor[Tailor] to handle OpenShift templates and keep OpenDevStack resources in sync. Please see its https://github.com/opendevstack/tailor#installation[installation instructions] for your platform. The following lists the version requirements:

|===
| OpenDevStack version | Tailor version

| 3.x
| >= 1.1.3

| 2.x
| >= 0.13.1

| 1.2.x
| = 0.9.3

| 1.1.x
| = 0.9.3

| 1.0.x
| = 0.9.1

| 0.1.x
| = 0.8
|===

== Infrastructure

If you are want to install on your local machine, please review xref:administration:local-install-requirements.adoc[local installation requirements].

=== Atlassian Tools
At this stage you can setup the Atlassian tools if they do not exist yet, or modify them as needed.

WARNING: Documentation for this is missing.

After Crowd is running, ensure that there is a user corresponding to the `CD_USER_ID_B64`/`CD_USER_PWD_B64` parameters in `ods-core.env`.

=== OpenShift cluster
At this stage you can setup the OpenShift cluster if it does not exist yet.

WARNING: Documentation for this is missing.

TIP: If you are on Linux, `oc cluster up` will do the trick.

== Bitbucket Repoisitories

On Bitbucket, there must be an `OPENDEVSTACK` project filled with the necessary repositories such as `ods-core`. To set them up, use:

[source,sh]
----
make prepare-bitbucket-repos
----

Then, update them with the latest state so that they can be used e.g. from `BuildConfig` resources in OpenShift:
[source,sh]
----
make sync-repos
----

You also need to update `ods-configuration`, which can be done via:
[source,sh]
----
git push -u origin master
----

== OpenDevStack environment in OpenShift

=== Central ODS project

OpenDevStack needs one central `ods` project in OpenShift, which will hold all shared resources such as images or deployments.

In `ods-core` run:
[source,sh]
----
make install-ods-project
----

TIP: In certain situations, you may want to pick a different name for the central namespace, e.g. for testing purposes or trying two versions of ODS next to each other. To do so, you need to run this and the following commands with `make NAMESPACE=foo <target>`.


=== Nexus

A central Nexus deployment is used to proxy packages and to store artifacts.

In `ods-core` run:
[source,sh]
----
make install-nexus
----

Afterwards, run the initial configuration:
[source,sh]
----
make configure-nexus
----

WARNING: The `configure-nexus` target is not idempotent yet, so it cannot be used for upgrading!

=== SonarQube

A central SonarQube deployment is used to analyze source code.

In `ods-core` run:
[source,sh]
----
make install-sonarqube
----

This will launch an instance of SonarQube.
The script will prompt for a new admin password, set it and create an auth token to be used by the Jenkins pipelines.
Both values can be written into `ods-configuration/ods-core.env`, which you then need to commit and push before continuing.

=== Jenkins

Central Jenkins images (master, agent, webhook proxy) are used by every ODS project.

In `ods-core` run:
[source,sh]
----
make install-jenkins
----

=== Document Generation service
At this stage you can setup or modify the image stream for the Document Generation service.

In `ods-core` run:
[source,sh]
----
make install-doc-gen
----

=== Provisioning Application
At this stage you can setup or modify the provisioning application.

In `ods-core` run:
[source,sh]
----
make install-provisioning-app
----


Congratulations! At this point you should have a complete ODS installation. Try it out by provisioning a new project with the provisioning application.
