apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.collector.name }}
  name: {{ .Values.collector.name }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "%s:%s" .Values.collector.name .Values.collector.odsImageTag }}
  postCommit: {}
  resources:
    limits:
      cpu: {{ .Values.buildConfig.cpuLimit }}
      memory: {{ .Values.buildConfig.memLimit }}
    requests:
      cpu: {{ .Values.buildConfig.cpuRequest }}
      memory: {{ .Values.buildConfig.memRequest }}
  runPolicy: Serial
  source:
    contextDir: opentelemetry-collector/docker
    git:
      uri: {{ .Values.collector.repoBase }}/{{ .Values.collector.odsBitBucketProject }}/ods-core.git
      ref: {{ .Values.collector.odsGitRef }}
    sourceSecret:
      name: cd-user-token
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: otel/opentelemetry-collector-k8s:{{ .Values.collector.collectorImageTag }}
      forcePull: true
      noCache: true
  successfulBuildsHistoryLimit: 5
