apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlphttp:
        endpoint: ${OTLP_API_ENDPOINT}
        headers:
          Authorization: "${OTLP_API_TOKEN}"
      debug:
        verbosity: normal
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp]
        metrics:
          exporters: [debug]
          processors: [memory_limiter, batch]
          receivers: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
