// BuildConfig environment variables
def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
def projectId = env.PROJECT_ID
def componentId = env.COMPONENT_ID.toLowerCase()

// Jenkins DeploymentConfig environment variables
def dockerRegistry
node {
  dockerRegistry = env.DOCKER_REGISTRY
}

def conts = containerTemplate(
  name: 'jnlp',
  image: "${dockerRegistry}/${odsNamespace}/jenkins-agent-base:${odsImageTag}",
  workingDir: '/tmp',
  alwaysPullImage: true,
  args: ''
)
def podLabel = "delete-component-${componentId}-from-${projectId}"

podTemplate(
  label: podLabel,
  cloud: 'openshift',
  containers: [conts],
  volumes: [],
  serviceAccount: 'jenkins'
) {
  node(podLabel) {
    stage('delete components') {
      currentBuild.description = "ODS Build #${env.BUILD_NUMBER} delete component '${componentId}' in project: ${projectId}"
      sh "oc delete all -n ${projectId}-dev -l app=${projectId}-${componentId}"
      sh "oc delete all -n ${projectId}-test -l app=${projectId}-${componentId}"
      sh "oc delete all -n ${projectId}-cd -l app=${projectId}-${componentId}"
    }
  }
}
