// BuildConfig environment variables
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
def projectId = env.PROJECT_ID
def componentId = env.COMPONENT_ID.toLowerCase()

// Jenkins DeploymentConfig environment variables
def dockerRegistry
node {
  dockerRegistry = env.DOCKER_REGISTRY
}

def conts = containerTemplate(
  name: 'jnlp',
  image: "${dockerRegistry}/cd/jenkins-slave-base:${odsImageTag}",
  workingDir: '/tmp',
  alwaysPullImage: true,
  args: ''
)
def podLabel = "delete-component-${componentId}-from-${projectId}"

podTemplate(
  label: podLabel,
  cloud: 'openshift',
  containers: [conts],
  volumes: [],
  serviceAccount: 'jenkins'
) {
  node(podLabel) {
    stage('Checkout') {
      checkout scm
    }
    stage('delete component') {
      sh "sh delete-components/delete-component.sh -p ${option.project_id} -c ${option.component_id}"
    }
  }
}
