= Nexus 3

Nexus 3 is an open source repository management platform developed by Sonatype to host and provide different registry and repository formats to store software artifacts.

This repository contains the logic and configuration for a central Nexus 3 repository instance to store build artifacts, provided by Jenkins jobs or provide access to shared and proxied repositories.

== Setup

The OpenShift templates are located in `ocp-config` and can be compared with the OC cluster using https://github.com/opendevstack/tailor[tailor]. For example, run `cd ocp-config && tailor status` to see if there is any drift between current and desired state.

You are also able to use the script `prepare-nexus.sh` located in the `infrastructure-setup/scripts` folder of this repository.
You will have to customize the script to match your target environment.

If you have a running Nexus 3 instance and you only want to add scripted resources, take a look at the `create-nexus-resources.sh` script. +
Inside this script you will find curl calls, that are used to run scripts in the Nexus 3 scripting API. +
The called scripts are located in the `json` subfolder and can be customized by your need. +
*Please keep in mind, that the user, who is provided in the curl calls has to have script execution rights in Nexus 3!*

The `createProjectSpecificAccess.json` contains the logic to create a project specific nexus user to isolate project artifacts from each other. +
The logic uses content selectors with an expression that uses the `path` to identify repos, that belong to one project, so you will have to specify a naming convention, if you use private repositories and isolated projects.

You can modify the used expression in the `createProjectSpecificAccess.json` script if it doesn't match your requirements and upload it to Nexus 3 with the related curl call.

ODS uses local Nexus 3 users out-of-the-box. If you want to use your internal authorization and authentication system, you will have to modify the scripts, so no user is created and the created privilege as added to your desired role.

== Administration

There is an `admin` user which is allowed to administer the whole Nexus 3 instance. The initial random password generated by Nexus 3 can be retrieved from within the pod.
It's located under `/nexus-data/admin.password`.

General help how to administer a Nexus 3 can be found at the https://help.sonatype.com/repomanager3[Sonartype page]

== Manual steps performed after booting the instance
. Admin password changed.
. Developer user password changed and amended in `ods-configuration` env files.
. Adjusted the needed proxy repositories and adjusted the OpenDevStack-Developer role, so the role has read rights to all needed repositories.
. Created an user for the provisioning app with script execution rights and adjusted the Nexus credentials used in the provisioning app.


