apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-postgresql
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "%s-postgresql:%s" .Values.global.appName .Values.global.odsImageTag }}
  postCommit: {}
  resources:
    limits:
      cpu: {{ .Values.buildConfig.cpuLimit }}
      memory: {{ .Values.buildConfig.memLimit }}
    requests:
      cpu: {{ .Values.buildConfig.cpuRequest }}
      memory: {{ .Values.buildConfig.memRequest }}
  runPolicy: Serial
  source:
    contextDir: sonarqube/docker
    git:
      uri: {{ .Values.global.repoBase }}/{{ .Values.global.odsBitBucketProject }}/ods-core.git
      ref: {{ .Values.global.odsGitRef }}
    sourceSecret:
      name: cd-user-token
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.database
      from:
        kind: DockerImage
        name: {{ .Values.global.sonarDatabaseImage}}
      forcePull: true
      noCache: true
  successfulBuildsHistoryLimit: 5
