apiVersion: v1
data:
  database-password: {{ .Values.global.sonarDatabasePasswordB64 }}
kind: Secret
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-postgresql
type: Opaque
