apiVersion: v1
kind: Secret
data:
  admin-password: {{ .Values.global.sonarAdminPasswordB64 }}
  {{ if ( eq .Values.sonarqube.sonarAuthSaml "true" )}}
  saml-provider-id: {{ .Values.sonarqube.sonarAuthSamlProviderIdB64 }}
  saml-login-url: {{ .Values.sonarqube.sonarAuthSamlLoginUrlB64 }}
  saml-cert: {{ .Values.sonarqube.sonarAuthSamlCertficateB64 }}
  {{ end }}
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-app
type: Opaque
