apiVersion: v1
data:
  database-password: {{ .Values.global.sonarDatabasePasswordB64 }}
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}-postgresql
type: Opaque