apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    deploymentconfig: {{ .Values.global.appName }}
  sessionAffinity: None
  type: ClusterIP
