apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  labels:
    app: {{ .Values.global.appName }}
    template: postgresql-persistent-template
  name: {{ .Values.global.appName }}-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ .Values.global.appName }}-postgresql
  sessionAffinity: None
  type: ClusterIP
