{{- if .Values.apis.projects.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-projects-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: projects-config
data:
  API_PROJECTS_MINIEDP_PROVISION_WORKFLOW_NAME: {{ .Values.apis.projects.workflowName | quote }}
  API_PROJECTS_LOCATIONS: {{ .Values.apis.projects.locations | quote }}
{{- end }}
