apiVersion: v1
kind: Template
metadata:
  name: elasticsearch-ephemeral-node-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      cluster: ${CLUSTER_NAME}
      component: ${COMPONENT_NAME}
      elasticsearchnode: ${COMPONENT_NAME}
    name: ${COMPONENT_NAME}
  spec:
    ports:
    - name: elasticsearch-default-restful-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: elasticsearch-default-transport-tcp
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      cluster: ${CLUSTER_NAME}
      component: ${COMPONENT_NAME}
      deploymentconfig: ${COMPONENT_NAME}
      elasticsearchnode: ${COMPONENT_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      cluster: ${CLUSTER_NAME}
      component: ${COMPONENT_NAME}
    name: ${COMPONENT_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      cluster: ${CLUSTER_NAME}
      component: ${COMPONENT_NAME}
      deploymentconfig: ${COMPONENT_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          cluster: ${CLUSTER_NAME}
          component: ${COMPONENT_NAME}
          deploymentconfig: ${COMPONENT_NAME}
          elasticsearchnode: ${COMPONENT_NAME}
      spec:
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: ${ELASTICSEARCH_MASTER_COMPONENT}-credentials
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: ${ELASTICSEARCH_MASTER_COMPONENT}-credentials
          - name: ELASTICSEARCH_CERTIFICATE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: certificate-password
                name: ${ELASTICSEARCH_MASTER_COMPONENT}-credentials
          - name: DISCOVERY_SEED_HOSTS
            value: ${ELASTICSEARCH_MASTER_COMPONENT}.${NAMESPACE}.svc
          - name: ELASTICSEARCH_CLUSTERNAME
            value: ${CLUSTER_NAME}
          image: shared-services/elasticsearch:7.0.0
          imagePullPolicy: Always
          name: ${COMPONENT_NAME}
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${COMPONENT_NAME}
        from:
          kind: ImageStreamTag
          name: elasticsearch:7.0.0
          namespace: shared-services
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
parameters:
- description: Name of the elastic search deployment/node
  name: COMPONENT_NAME
  required: true
- description: Name of the elastic search cluster, Should be the same for all nodes
  name: CLUSTER_NAME
  required: true
- description: Name of the elastic search cluster, Should be the same for all nodes
  name: NAMESPACE
  required: true
- description: ElasticSearch Master node component name
  name: ELASTICSEARCH_MASTER_COMPONENT
  required: true
