FROM public.ecr.aws/docker/library/postgres:16-alpine

# Install oc client tool
RUN if [ -f /etc/os-release ] && grep -q "alpine" /etc/os-release; then \
      apk add --no-cache curl && \
      curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz -C /usr/local/bin && \
      apk del curl; \
    else \
      yum install -y openshift-clients && \
      yum clean all; \
    fi

