apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-postgresql-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "chart.fullname" . }}-postgresql:5432/{{ .Values.postgresql.databaseName }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.databaseUser | quote }}
