apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  name: {{ include "chart.fullname" . }}-postgresql
type: Opaque
data:
  database-name: {{ .Values.postgresql.databaseNameB64 }}
  database-user: {{ .Values.postgresql.databaseUserB64 }}
  database-password: {{ .Values.postgresql.databasePasswordB64 }}
  superuser-password: {{ .Values.postgresql.superuserPasswordB64 }}
