apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  name: {{ include "chart.fullname" . }}-postgresql
type: Opaque
data:
  ODS_API_SERVICE_DB_NAME: {{ .Values.postgresql.databaseNameB64 }}
  ODS_API_SERVICE_DB_USER: {{ .Values.postgresql.databaseUserB64 }}
  ODS_API_SERVICE_DB_PASSWORD: {{ .Values.postgresql.databasePasswordB64 }}
  ODS_API_SERVICE_DB_SUPERUSER_PASSWORD: {{ .Values.postgresql.superuserPasswordB64 }}
