= Jenkins

OpenDevStack provides several customized Jenkins container images based on the official OpenShift images.

In `ods-core/jenkins`, you find the following directory structure:

.Table Directories

|===
|Directory | Description

|master
|Dockerfile for Jenkins Master

|ocp-config
|OpenShift templates and Tailorfile

|slave-base
|Dockerfile and customization for Jenkins Slave Images

|webhook-proxy
|Dockerfile and source code for Bitbucket webhook proxy

|===


== Jenkins Master

The following customizations are applied to enable more automatic deployment of Jenkins.

=== Configured Plugins

We have included some base plugins
,===
include::{examplesdir}/plugins.txt[]
,===

=== Init groovy scripts

Jenkins offers to deploy https://wiki.jenkins.io/display/JENKINS/Post-initialization+script[ post-initialization ] scripts.

.Table Post-Initialization Scripts
|===
|Script | Description

|url.groovy | Sets the Jenkins location based on the OpenShift route
|sonarqube.groovy | Sets the SonarQube server URL and auth token based on the exposed environment variables
|ods-jenkins-shared-library.groovy | Registers `ods-jenkins-shared-library` as a global library
|ods-mro-jenkins-shared-library.groovy | Registers `ods-mro-jenkins-shared-library` as a global library

|===

The following environment variables must be available to Jenkins:

SONAR_SERVER_URL::
specifies the location of the SonarQube server.
SONAR_AUTH_TOKEN::
this is the SonarQube auth token that is generated when deploying and configuring sonarqube

=== Mail Sending

We enable (in Dockerfile) the sending of mails to unknown users and users without read rights.

== Jenkins Slave

We have a base image for different jenkins slaves.
The concrete slave images are then configured as part of the quickstarters.
The base image contains the following customizations

* SonarQube Scanner
* SonarQube CNES Report Plugin
* Tailor
* Setting of Enterprise Proxy

When the container image is built, it fetches automatically the OpenShift root CA certificate and stores it, so that the `oc`-cli tool
can pick it up later and also adds the base domain wildcard certificate to the Java certificate store.

The setting of the enterprise proxy takes care that Jenkins slave works also on OpenShift clusters in enterprises that use a web proxy.

== Webhook Proxy

Provides one endpoint accepting webhooks from BitBucket and forwards them to the
corresponding Jenkins pipeline (which is determined based on the branch name).
If there is no corresponding pipeline yet, it will be created on the fly. Once a
branch is deleted or a pull request declined/merged, the corresponding Jenkins
pipeline is deleted as well.

=== Usage

Go to "Repository Settings > Webhooks" and click on "Create webhook". Enter
`Jenkins` as Title and the route URL (see following <<Setup>> section) as
URL. Under "Repository events", select `Push`. Under "Pull request events",
select `Merged` and `Declined`. Save your changes and you're done! Any other
webhooks already setup to trigger Jenkins are not needed anymore and should be
deactivated or deleted.

=== Setup

Run `tailor update` in `ocp-config`. This will create `BuildConfig` and
`ImageStream` in the central `cd` namespace. Next, you will have to create a
`DeploymentConfig`, `Service` and `Route` in the namespace your Jenkins instance
runs.

