= Jenkins Master

The following customizations are applied to enable more automatic deployment of Jenkins.

== Configured Plugins

We have included some base plugins
,===
include::{examplesdir}/plugins.txt[]
,===

== Init scripts

Jenkins offers to deploy https://wiki.jenkins.io/display/JENKINS/Post-initialization+script[post-initialization] scripts.

.Table Post-Initialization Scripts
|===
|Script | Description

|url.groovy | Sets the Jenkins location based on the OpenShift route
|sonarqube.groovy | Sets the SonarQube server URL and auth token based on the exposed environment variables
|ods-jenkins-shared-library.groovy | Registers `ods-jenkins-shared-library` as a global library

|===

The following environment variables must be available to Jenkins:

SONAR_SERVER_URL::
specifies the location of the SonarQube server.
SONAR_AUTH_TOKEN::
this is the SonarQube auth token that is generated when deploying and configuring sonarqube

== Mail Sending

In the Dockerfile, sending of mails to unknown users and users without read rights is enabled.
