def dockerRegistry

node {
  dockerRegistry = env.DOCKER_REGISTRY
}
def conts = containerTemplate( 
            name: 'jnlp',
            image: "${dockerRegistry}/cd/jenkins-slave-base",
            workingDir: '/tmp',
            alwaysPullImage: true,
            args: ''
        )

def podLabel = "check_ocp_secure_routes"
podTemplate(
      label: podLabel,
      cloud: 'openshift',
      containers: [conts],
      volumes: [],
      serviceAccount: 'jenkins'
    ) {
        node(podLabel) {
          stage('checkout'){
            checkout scm
          }
          stage('check_ocp_secure_routes.sh'){
            sh "sh check-ocp-secure-routes/check_ocp_secure_routes.sh"
        }
      }
}