#!/bin/bash
#
# This script copies any init.groovy.d files under the control of OpenDevStack,
# then delegates to the original run script of the base image.

echo "Booting Jenkins ..."

echo "Copy init.groovy.d files ..."
source_init_groovy_dir="/opt/openshift/configuration/init.groovy.d"
target_init_groovy_dir="${JENKINS_HOME}/init.groovy.d"
for f in ${source_init_groovy_dir}/*.groovy; do
    fileName=${f#${source_init_groovy_dir}'/'}
    echo "---> Copying ${source_init_groovy_dir}/${fileName} to ${target_init_groovy_dir}/${fileName} ..."
    cp "${source_init_groovy_dir}/${fileName}" "${target_init_groovy_dir}/${fileName}"
done

echo "Copy fixed version of openshift-sync plugin (https://github.com/opendevstack/ods-core/issues/86) ..."
cp /opt/openshift/openshift-sync.jar /var/lib/jenkins/plugins/openshift-sync/WEB-INF/lib/openshift-sync.jar

/usr/libexec/s2i/run
