#!/bin/bash
#
# This script copies any init.groovy.d files under the control of OpenDevStack,
# then delegates to the original run script of the base image.
set -ue

echo "Deleting .kube to avoid weird caching issues (see https://github.com/opendevstack/ods-core/issues/473)"
rm -rf $HOME/.kube || true

# Openshift default CA. See https://docs.openshift.com/container-platform/3.11/dev_guide/secrets.html#service-serving-certificate-secrets
SERVICEACCOUNT_CA='/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt'
if [[ -f $SERVICEACCOUNT_CA ]]; then
  echo "INFO: found $SERVICEACCOUNT_CA"
  echo "INFO: importing into cacerts"
  $JAVA_HOME/bin/keytool -importcert -v -trustcacerts -alias service-ca -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -file "$SERVICEACCOUNT_CA" -noprompt
else
  echo "INFO: could not find '$SERVICEACCOUNT_CA'"
  echo "INFO: skip import"
fi

target_init_groovy_dir="${JENKINS_HOME}/init.groovy.d"
if [ -d "$target_init_groovy_dir" ] ; then
    # If the target dir does not exist yet, files under
    # /opt/openshift/configuration will be copied later by /usr/libexec/s2i/run.
    echo "Copy init.groovy.d files ..."
    source_init_groovy_dir="/opt/openshift/configuration/init.groovy.d"
    for f in ${source_init_groovy_dir}/*.groovy; do
        fileName=${f#${source_init_groovy_dir}'/'}
        echo "---> Copying ${source_init_groovy_dir}/${fileName} to ${target_init_groovy_dir}/${fileName} ..."
        cp "${source_init_groovy_dir}/${fileName}" "${target_init_groovy_dir}/${fileName}"
    done
    echo "Remove legacy init.groovy.d files ..."
    rm "${target_init_groovy_dir}/ods-mro-jenkins-shared-library.groovy" &> /dev/null || true
fi

echo "Copy grape config and amending with Nexus ..."
if [ -n "${NEXUS_URL:-}" ]; then
  nexusUrl="${NEXUS_URL}"
elif [ -n "${NEXUS_HOST:-}" ]; then
  nexusUrl="${NEXUS_HOST}"
else
  echo "ERROR: Neither NEXUS_URL or NEXUS_HOST present."
  exit 1
fi
NEXUS_SHORT=$(echo "${nexusUrl}" | sed -e "s|https://||g" | sed -e "s|http://||g")
mkdir -p $HOME/.groovy
cp /opt/openshift/configuration/grapeConfig.xml $HOME/.groovy/
sed -i.bak -e "s|__NEXUS_HOST_NO_URL|$NEXUS_SHORT|g" $HOME/.groovy/grapeConfig.xml
sed -i.bak -e "s|__NEXUS_HOST|$nexusUrl|g" $HOME/.groovy/grapeConfig.xml
sed -i.bak -e "s|__NEXUS_USER|$NEXUS_USERNAME|g" $HOME/.groovy/grapeConfig.xml
sed -i.bak -e "s|__NEXUS_PW|$NEXUS_PASSWORD|g" $HOME/.groovy/grapeConfig.xml

echo "Booting Jenkins ..."
/usr/libexec/s2i/run
