apiVersion: v1
kind: Template
labels:
  template: secrets-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: cd-user-token
  type: kubernetes.io/basic-auth
  data:
    password: ${CD_USER_PWD_B64}
    username: ${CD_USER_ID_B64}
parameters:
- name: CD_USER_PWD_B64
  description: cd_user password (base64 encoded)
  required: true
- name: CD_USER_ID_B64
  description: cd_user name (base64 encoded)
  required: true
