apiVersion: v1
kind: Template
parameters:
- name: ODS_BITBUCKET_PROJECT
  value: opendevstack
- name: ODS_IMAGE_TAG
  required: true
- name: ODS_GIT_REF
  required: true
- name: REPO_BASE
  required: true
- name: NEXUS_FROM_IMAGE
  required: true
- name: NEXUS_BUILD_CPU_REQUEST
  value: 200m
- name: NEXUS_BUILD_CPU_LIMIT
  value: "1"
- name: NEXUS_BUILD_MEMORY_REQUEST
  value: 1Gi
- name: NEXUS_BUILD_MEMORY_LIMIT
  value: 2Gi
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nexus:${ODS_IMAGE_TAG}
    postCommit: {}
    resources:
      limits:
        cpu: ${NEXUS_BUILD_CPU_LIMIT}
        memory: ${NEXUS_BUILD_MEMORY_LIMIT}
      requests:
        cpu: ${NEXUS_BUILD_CPU_REQUEST}
        memory: ${NEXUS_BUILD_MEMORY_REQUEST}
    runPolicy: Serial
    source:
      contextDir: nexus/docker
      git:
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-core.git
        ref: ${ODS_GIT_REF}
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        forcePull: true
        noCache: true
        from:
          kind: DockerImage
          name: ${NEXUS_FROM_IMAGE}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
