apiVersion: v1
kind: Template
parameters:
- name: ODS_NAMESPACE
  value: ods
- name: ODS_IMAGE_TAG
  required: true
- name: NEXUS_NAME
  value: nexus
- name: NEXUS_CPU_REQUEST
  value: 200m
- name: NEXUS_CPU_LIMIT
  value: "1"
- name: NEXUS_MEMORY_REQUEST
  value: 2560Mi
- name: NEXUS_MEMORY_LIMIT
  value: 4Gi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NEXUS_NAME}
    name: ${NEXUS_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${NEXUS_NAME}
      deploymentconfig: ${NEXUS_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NEXUS_NAME}
          deploymentconfig: ${NEXUS_NAME}
      spec:
        containers:
        - image: ${ODS_NAMESPACE}/${NEXUS_NAME}:${ODS_IMAGE_TAG}
          imagePullPolicy: Always
          name: ${NEXUS_NAME}
          ports:
          - containerPort: 8081
            protocol: TCP
          resources:
            limits:
              cpu: ${NEXUS_CPU_LIMIT}
              memory: ${NEXUS_MEMORY_LIMIT}
            requests:
              cpu: ${NEXUS_CPU_REQUEST}
              memory: ${NEXUS_MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: volume-fmcqy
          - mountPath: /nexus-backup
            name: volume-8dv8t
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-fmcqy
          persistentVolumeClaim:
           claimName: nexus-data
        - name: volume-8dv8t
          persistentVolumeClaim:
            claimName: nexus-db-backup
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NEXUS_NAME}
        from:
          kind: ImageStreamTag
          name: ${NEXUS_NAME}:${ODS_IMAGE_TAG}
          namespace: ${ODS_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
