apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    lookupPolicy:
      local: false
