apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: nexus3
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_DATA}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus-data-extended
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${NEXUS_DATA_CAPACITY}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_BACKUP}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus-db-backup
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${NEXUS_BACKUP_CAPACITY}
parameters:
- name: STORAGE_PROVISIONER
  required: true
- name: STORAGE_CLASS_DATA
  required: true
- name: STORAGE_CLASS_BACKUP
  required: true
- name: NEXUS_DATA_CAPACITY
  value: 60Gi
- name: NEXUS_BACKUP_CAPACITY
  value: 10Gi
