apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: NEXUS_NAME
  value: nexus
- name: NEXUS_DOCKER_NAME
  value: docker-group
- name: NEXUS_HOST
  description: Nexus host without protocol - which is attached based on the configuration in the route.yml
  required: true
- name: OPENSHIFT_APPS_BASEDOMAIN
  description: the domain of routes exposed on OCP.
  required: true
- name: ODS_NAMESPACE
  description: Central ODS namespace in OpenShift.
  required: true
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NEXUS_NAME}
    name: ${NEXUS_NAME}
  spec:
    host: ${NEXUS_HOST}
    port:
      targetPort: 8081-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NEXUS_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NEXUS_NAME}
    name: ${NEXUS_DOCKER_NAME}
  spec:
    host: ${NEXUS_DOCKER_NAME}-${ODS_NAMESPACE}${OPENSHIFT_APPS_BASEDOMAIN}
    port:
      targetPort: 5000-docker
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NEXUS_NAME}
      weight: 100
    wildcardPolicy: None
