apiVersion: v1
kind: Template
metadata:
  name: nexus3
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    host: ${NEXUS_HOST}
    port:
      targetPort: 8081-tcp
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: nexus3
      weight: 100
    wildcardPolicy: None
parameters:
- name: NEXUS_HOST
  description: Nexus host without protocol - which is attached based on the configuration in the route.yml
  required: true
