apiVersion: v1
kind: Template
metadata:
  name: nexus3
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: nexus-oauth
    labels:
      app: nexus3
    name: nexus3
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
