apiVersion: v1
kind: Template
metadata:
  name: nexus3
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    ports:
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
