= Infrastructure Setup

The infrastructure setup part contains the scripts to setup OpenDevstack.
It uses https://www.ansible.com[Ansible] for installing the Atlassian tools and the provisioning app (including https://www.rundeck.com/open-source[Rundeck].
Setting up an https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html#id2[Ansible control host] is beyond the scope of this document.

Each individual component is set-up using a seperate playbook. So you can decide which playbooks to run, depending on your current environment.

IMPORTANT: Note that for a local installation for development, in general you do not need to run the playbooks yourself, since
they are called by the installation script  _setup-local-environment.sh_, as described in the
_Guides and Tutorials_ -> _Local Installation_ guide.

== The different playbooks

We have different playbooks depending on the environment in which you install the Atlassian tools and Rundeck.
The playbooks depend on roles. The roles provide variables for customization. The different variables can be looked up under each role at `default/main.yml`.

.General Playbooks
bitbucket.yml::
Sets up Atlassian Bitbucket
confluence.yml::
Sets up Atlassian Confluence
confluence_enable_sso.yml::
After basic setup of Crowd and Confluence setup, enable SSO functionality.
crowd.yml::
Sets up Atlassian Crowd as an Identity and SSO provider
jira.yml::
Sets up Atlassian Jira
jira_enable_sso.yml::
After basic setup of Crowd and Jira setup, enable SSO functionality.
postgresql.yml::
Sets up a (local) PostgreSQL for use with Atlassian tools.
rundeck.yml::
Sets up rundeck.
schemas.yml::
Sets up the required schemas for Atlassian tools

Beside the basic playbooks, it might be required to run additional playbooks if you setup the Atlassian tools on AWS.

.Special Plabyooks

crowd_post_setup.yml::
Takes care that login to crowd is possible by inserting the AWS LB IP addresses into the database tables.




