apiVersion: v1
kind: Template
parameters:
- name: TAILOR_NAMESPACE
  required: true
- name: PROV_APP_IMAGE
  required: true
- name: PROV_APP_IMAGE_PULL_POLICY
  required: true
- name: PROV_APP_CPU_REQUEST
  value: 100m
- name: PROV_APP_CPU_LIMIT
  value: "1"
- name: PROV_APP_MEMORY_REQUEST
  value: 512Mi
- name: PROV_APP_MEMORY_LIMIT
  value: 1Gi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ods-provisioning-app
    name: ods-provisioning-app
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ods-provisioning-app
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ods-provisioning-app
      spec:
        containers:
        - image: ""
          imagePullPolicy: ${PROV_APP_IMAGE_PULL_POLICY}
          name: ods-provisioning-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: ${PROV_APP_CPU_LIMIT}
              memory: ${PROV_APP_MEMORY_LIMIT}
            requests:
              cpu: ${PROV_APP_CPU_REQUEST}
              memory: ${PROV_APP_MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/provision/history
            name: volume-history
          - mountPath: /config
            name: volume-ikfik
          - mountPath: /quickstarters
            name: volume-qs
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-history
          persistentVolumeClaim:
            claimName: prov-history
        - configMap:
            defaultMode: 420
            items:
            - key: properties
              path: application.properties
            name: application.properties
          name: volume-ikfik
        - configMap:
            defaultMode: 420
            items:
            - key: properties
              path: quickstarters.properties
            name: quickstarters.properties
          name: volume-qs
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ods-provisioning-app
        from:
          kind: ImageStreamTag
          name: ${PROV_APP_IMAGE}
          namespace: ${TAILOR_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
