apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ods-provisioning-app
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ods-provisioning-app
  spec:
    lookupPolicy:
      local: false
