apiVersion: v1
kind: Template
parameters:
- name: STORAGE_PROVISIONER
  description: storage class provisioner. For AWS this could be kubernetes.io/aws-ebs. Leave empty for local (e.g. vagrant) deployments
  value: ""
- name: STORAGE_CLASS_DATA
  description: storage class for data. For AWS this could be gp2. Leave empty for local (e.g. vagrant) deployments
  value: ""
- name: PROV_APP_HISTORY_CAPACITY
  value: 20Mi
labels:
  app: ods-provisioning-app
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_DATA}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    finalizers:
    - kubernetes.io/pvc-protection
    name: prov-history
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${PROV_APP_HISTORY_CAPACITY}
    volumeMode: Filesystem
