apiVersion: template.openshift.io/v1
kind: Template
parameters:
    - name: PROV_APP_CROWD_PASSWORD
      required: true
      description: password of the crowd app to authenticate the provision app against
    - name: PROV_APP_JASYPT_PASSWORD
      required: true
    - name: PROV_APP_MAIL_PASSWORD
      required: true
      description: The password to authenticate against the mail server
    - name: PROV_APP_MAIL_USERNAME
      required: true
      description: The username to authenticate against the mail server
    - name: PROV_APP_CROWD_APPLICATION_NAME
      value: provision
labels:
    app: ods-provisioning-app
objects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: ods-provisioning-app
      stringData:
        CROWD_APPLICATION_NAME=${PROV_APP_CROWD_APPLICATION_NAME}
        CROWD_APPLICATION_PASSWORD=${PROV_APP_CROWD_PASSWORD}
        JASYPT_ENCRYPTOR_PASSWORD=${PROV_APP_JASYPT_PASSWORD}
        SPRING_MAIL_USERNAME=${PROV_APP_MAIL_USERNAME}
        SPRING_MAIL_PASSWORD=${PROV_APP_MAIL_PASSWORD}
