apiVersion: v1
kind: Template
labels:
  app: ods-provisioning-app
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ods-provisioning-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ods-provisioning-app
    sessionAffinity: None
    type: ClusterIP
