apiVersion: v1
kind: Template
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack  
- name: ODS_IMAGE_TAG
  description: OpenDevStack image tag to use.
  required: true
- name: ODS_GIT_REF
  description: Git ref to use for source code.
  required: true
- name: REPO_BASE
  description: repository base url. In case bitbucket is used, needs to include /scm - so it's the path in front on opendevstack/..
  required: true
- name: DOC_GEN_FROM_IMAGE
  description: Base image for Documentation generation service
  required: true
- name: DOC_GEN_BUILD_CPU_REQUEST
  value: "200m"
- name: DOC_GEN_BUILD_CPU_LIMIT
  value: "1"
- name: DOC_GEN_BUILD_MEMORY_REQUEST
  value: 1Gi
- name: DOC_GEN_BUILD_MEMORY_LIMIT
  value: 2Gi
- name: APP_DNS
  description: OpenShift application base dns - used for grabbing the root ca and adding into the agent
labels:
  app: ods-doc-gen-svc
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ods-doc-gen-svc
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'ods-doc-gen-svc:${ODS_IMAGE_TAG}'
    postCommit: {}
    resources:
      limits:
        cpu: ${DOC_GEN_BUILD_CPU_LIMIT}
        memory: ${DOC_GEN_BUILD_MEMORY_LIMIT}
      requests:
        cpu: ${DOC_GEN_BUILD_CPU_REQUEST}
        memory: ${DOC_GEN_BUILD_MEMORY_REQUEST}
    runPolicy: Serial
    source:
      type: Git
      contextDir: ods-document-generation-svc/docker
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-core.git
      sourceSecret:
        name: cd-user-token
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: true
        noCache: true
        env:
          - name: APP_DNS
            value: ${APP_DNS}
        from:
          kind: DockerImage
          name: ${DOC_GEN_FROM_IMAGE}
    successfulBuildsHistoryLimit: 5
    triggers: []
