apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ods-doc-gen-svc
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ods-doc-gen-svc
  spec:
    lookupPolicy:
      local: false
