apiVersion: v1
kind: Template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: elasticsearch
    labels:
      app: shared-services
      component: elasticsearch
      template: bc-docker
  spec:
    dockerImageRepository: elasticsearch
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: shared-services
      component: airflow
      template: bc-docker
    name: airflow
  spec:
    dockerImageRepository: airflow
    lookupPolicy:
      local: false
