apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: cd-user-token
    labels:
      app: shared-services
  type: kubernetes.io/basic-auth
  data:
    username: ${CD_USER_ID}
    password: ${CD_USER_PWD}
parameters:
- name: CD_USER_ID
  description: cd_user username (base64 encoded)
  required: true
- name: CD_USER_PWD
  description: cd_user password (base64 encoded)
  required: true
