apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: prov-app
    name: prov-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: prov-app
    sessionAffinity: None
    type: ClusterIP
