---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }} 
data:
  application.yaml: |
{{ include "chart.application.yaml" . | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-db
  labels:
    {{- include "chart.labels" . | nindent 4 }} 
data:
  ODS_API_SERVICE_DB_DATASOURCE_URL: "jdbc:postgresql://{{ include "chart.fullname" . }}-postgresql:5432/{{ .Values.postgresql.databaseName }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-db-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  ODS_API_SERVICE_DB_NAME: {{ .Values.postgresql.databaseNameB64 }}
  ODS_API_SERVICE_DB_USER: {{ .Values.postgresql.databaseUserB64 }}
  ODS_API_SERVICE_DB_PASSWORD: {{ .Values.postgresql.databasePasswordB64 }}
