{{- include "chart.validate.all" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-application: {{ include (print $.Template.BasePath "/core/configmaps-application.yaml") . | sha256sum }}
        checksum/configmap-services: {{ include (print $.Template.BasePath "/core/configmaps-services.yaml") . | sha256sum }}
        checksum/configmap-external-services: {{ include (print $.Template.BasePath "/core/configmaps-external-services.yaml") . | sha256sum }}
        checksum/secret-application: {{ include (print $.Template.BasePath "/core/secrets-application.yaml") . | sha256sum }}
        checksum/secret-services: {{ include (print $.Template.BasePath "/core/secrets-services.yaml") . | sha256sum }}
        checksum/secret-external-services: {{ include (print $.Template.BasePath "/core/secrets-external-services.yaml") . | sha256sum }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "image.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            {{- if .Values.env.CERT_URLS }}
            - name: CERT_URLS
              value: {{ .Values.env.CERT_URLS | quote }}
            {{- end }}
            - name: OAUTH2_ISSUER
              value: {{ .Values.env.OAUTH2_ISSUER | quote }}
            - name: OAUTH2_AUDIENCE
              value: {{ .Values.env.OAUTH2_AUDIENCE | quote }}
            - name: OAUTH2_JWK_SET_URI
              value: {{ .Values.env.OAUTH2_JWK_SET_URI | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS | quote }}

            # Inject runtime environment grouped by functional domain:
            # application, services, and external-services.
          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}-application-config
            - secretRef:
                name: {{ include "chart.fullname" . }}-application-secrets
            - configMapRef:
                name: {{ include "chart.fullname" . }}-services-config
            - secretRef:
                name: {{ include "chart.fullname" . }}-services-secrets
            - configMapRef:
                name: {{ include "chart.fullname" . }}-external-services-config
            - secretRef:
                name: {{ include "chart.fullname" . }}-external-services-secrets

          livenessProbe:
            {{- toYaml .Values.probes.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.probes.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: spring-config
              mountPath: /home/default/config/

      affinity:
      {{- with .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
        {{- if eq .Values.podAntiAffinity "soft" }}
        podAntiAffinity: {{- include "common.affinities.pods.soft" . | nindent 10 }}
        {{- end }}
        {{- if eq .Values.podAntiAffinity "hard" }}
        podAntiAffinity: {{- include "common.affinities.pods.hard" . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: spring-config
          configMap:
            name: {{ .Release.Name }}-config
