---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-application-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: application-secrets
    ods.opendevstack.io/runtime-domain: application
type: Opaque
data:
{{ include "chart.applicationSecretData" . | nindent 2 }}
