---
# Internal services and API-specific sensitive runtime settings
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-services-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: services-secrets
    ods.opendevstack.io/runtime-domain: services
type: Opaque
{{- $servicesSecrets := include "chart.servicesSecretData" . | trim }}
data:
{{- if $servicesSecrets }}
{{ $servicesSecrets | nindent 2 }}
{{- else }}
  {}
{{- end }}