---
# Third-party and platform integration sensitive runtime settings
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-external-services-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-services-secrets
    ods.opendevstack.io/runtime-domain: external-services
type: Opaque
{{- $externalServicesSecrets := include "chart.externalServicesSecretData" . | trim }}
data:
{{- if $externalServicesSecrets }}
{{ $externalServicesSecrets | nindent 2 }}
{{- else }}
  {}
{{- end }}
