apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 2m
    labels:
      app: ods-provisioning-app
    name: ods-provisioning-app
  spec:
    host: ods-prov-app-${TAILOR_NAMESPACE}${OPENSHIFT_APPS_BASEDOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ods-provisioning-app
      weight: 100
    wildcardPolicy: None
parameters:
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
- name: TAILOR_NAMESPACE
  required: true
