apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-jira-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: jira-config
data:
{{- if gt (len .Values.externalServices.jira.instances) 0 }}
  JIRA_DEFAULT_INSTANCE: {{ .Values.externalServices.jira.defaultInstance | quote }}
  {{- range $name, $instance := .Values.externalServices.jira.instances }}
  JIRA_{{ $name | upper | replace "-" "_" }}_BASE_URL: {{ $instance.baseUrl | quote }}
  JIRA_{{ $name | upper | replace "-" "_" }}_CONNECTION_TIMEOUT: {{ $instance.connectionTimeout | quote }}
  JIRA_{{ $name | upper | replace "-" "_" }}_READ_TIMEOUT: {{ $instance.readTimeout | quote }}
  JIRA_{{ $name | upper | replace "-" "_" }}_TRUST_ALL: {{ $instance.trustAllCertificates | quote }}
  {{- end }}
{{- end }}
