kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: only-allow-namespace-ingress
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: "{{NAMESPACE}}"
        - podSelector: {}
  policyTypes:
    - Ingress