kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: only-allow-namespace-ingress
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              policy-group.network.openshift.io/ingress: ''
  policyTypes:
    - Ingress
