apiVersion: v1
kind: Template
metadata:
  name: check-insecure-routes
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: check-insecure-routes
  spec:
    schedule: "0 0 * * *"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: "cronjob-check-insecure-routes"
          spec:
            containers:
            - name: check-insecure-routes
              image: ${DOCKER_REGISTRY}/cd/jenkins-slave-base:${ODS_IMAGE_TAG}
              command: ["curl", "-k","-d", "{\"branch\": \"${ODS_GIT_REF}\",\"repository\": \"ods-core\",\"project\": \"opendevstack\",\"env\": [{\"name\":\"ODS_IMAGE_TAG\",\"value\":\"${ODS_IMAGE_TAG}\"}]}", "-X", "POST", "https://webhook-proxy-prov-cd${OPENSHIFT_APPS_BASEDOMAIN}/build?trigger_secret=${PIPELINE_TRIGGER_SECRET}&jenkinsfile_path=check-ocp-secure-routes/Jenkinsfile&component=ods-check-insecure-routes"]
            restartPolicy: Never
parameters:
- name: ODS_GIT_REF
  required: true
- name: ODS_IMAGE_TAG
  required: true
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
- name: PIPELINE_TRIGGER_SECRET
  required: true
- name: DOCKER_REGISTRY
  required: true
