---
# file: tasks/install.yml
# Top-level installer for Oracle JDK.
#


- name: fetch .rpm or .tar.gz files from Oracle site
  include: fetch.yml
  when: java_download_from_oracle

- block:

    - name: copy RPM from local
      copy:
        src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.rpm"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
      when: use_rpm

    - name: copy tarball from local
      copy:
        src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.tar.gz"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
      when: use_tarball

    - name: copy .dmg from local
      copy:
        src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.dmg"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"
      when: use_dmg

  when: not java_download_from_oracle



- name: delegate to RPM installation process
  include: use-rpm.yml
  when: use_rpm

- name: delegate to raw tarball installation process
  include: use-tarball.yml
  when: use_tarball

- name: delegate to Mac OS X dmg installation
  include: use-dmg.yml
  when: use_dmg

- block:

    - name: make sure /etc/profile.d exists
      file: path=/etc/profile.d  state=directory

    - name: export JAVA_HOME
      template:
        src:  ../templates/java_home.sh.j2
        dest: /etc/profile.d/java_home.sh
        mode: "a+x"

  when: java_set_javahome



- block:

    # No link creation is necessary on Mac OS X -- 
    # the package installer automatically creates symlinks in /usr/bin.

    - name: link "{{ java_install_dir }}/{{ java_default_link_name }} on rpm based systems for JDK8"
      file:
        src: "{{ java_install_dir }}/jdk{{ jdk_version }}-amd64"
        dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
        state: link
      when: java_version == 8 and use_rpm

    - name: link "{{ java_install_dir }}/{{ java_default_link_name }} on tarball based systems for JDK8"
      file:
        src: "{{ java_install_dir }}/jdk{{ jdk_version }}"
        dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
        state: link
      when: java_version == 8 and use_tarball

    - name: link "{{ java_install_dir }}/{{ java_default_link_name }} on rpm based systems for JDK > 8"
      file:
        src: "{{ java_install_dir }}/jdk-{{ jdk_version }}"
        dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
        state: link
      when: java_version != 8 and use_rpm

    - name: link "{{ java_install_dir }}/{{ java_default_link_name }} on tarball based systems for JDK > 8"
      file:
        src: "{{ java_install_dir }}/jdk-{{ jdk_version }}"
        dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
        state: link
      when: java_version != 8 and use_tarball

    - name: alternatives link for "java"
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/java"

    - name: alternatives link for "javac"
      alternatives:
        name: javac
        link: /usr/bin/javac
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/javac"

    - name: alternatives link for "jar"
      alternatives:
        name: jar
        link: /usr/bin/jar
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/jar"

    - name: check if "java_sdk" target exists
      stat: path=/usr/lib/jvm/java
      register: filecheck

    - name: alternatives link for "java_sdk"
      alternatives:
        name: java_sdk
        link: /usr/lib/jvm/java
        path: "{{ java_install_dir }}/{{ java_default_link_name }}"
      when: filecheck and filecheck.stat.exists

  become: yes
  when: ansible_os_family != "Darwin"



- name: remove temporary downloaded files, if requested
  file: path={{ item }} state=absent
  with_items:
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"
    - "{{ java_download_path }}/check-tarball-installed.sh"
  ignore_errors: true
  when: java_remove_download
