FROM public.ecr.aws/docker/library/postgres:18-alpine

USER root

# Install oc client (require libc6-compat to provice glibc compatibility)
RUN apk add --no-cache curl libc6-compat && \
    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz \
      | tar xz -C /usr/local/bin && \
    oc version

# Fix permissions only for the persistent data directory
RUN chgrp -R 0 /var/lib/postgresql && \
    chmod -R g+rwX /var/lib/postgresql
