participant OpenDevStack as A
participant "ACME GitHub OpenDevStack fork" as B
participant "ACME private repo" as C
A->>C: 2.x/v2.0 checkout

C->>C: new feature branch X
rnote right of C: develop and test

C-->>C: PR: branch X to production branch
rnote right of C: test production

C->>B: push branch X

B-->>A: PR: branch X to 2.x/v2.0
